// Code generated by 'go generate'; DO NOT EDIT.

package native

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")
	modntdll    = windows.NewLazySystemDLL("ntdll.dll")

	procContinueDebugEvent         = modkernel32.NewProc("ContinueDebugEvent")
	procDebugActiveProcess         = modkernel32.NewProc("DebugActiveProcess")
	procDebugActiveProcessStop     = modkernel32.NewProc("DebugActiveProcessStop")
	procDebugBreakProcess          = modkernel32.NewProc("DebugBreakProcess")
	procFlushInstructionCache      = modkernel32.NewProc("FlushInstructionCache")
	procGetThreadContext           = modkernel32.NewProc("GetThreadContext")
	procIsWow64Process             = modkernel32.NewProc("IsWow64Process")
	procQueryFullProcessImageNameW = modkernel32.NewProc("QueryFullProcessImageNameW")
	procReadProcessMemory          = modkernel32.NewProc("ReadProcessMemory")
	procResumeThread               = modkernel32.NewProc("ResumeThread")
	procSetThreadContext           = modkernel32.NewProc("SetThreadContext")
	procSuspendThread              = modkernel32.NewProc("SuspendThread")
	procVirtualQueryEx             = modkernel32.NewProc("VirtualQueryEx")
	procWaitForDebugEvent          = modkernel32.NewProc("WaitForDebugEvent")
	procWriteProcessMemory         = modkernel32.NewProc("WriteProcessMemory")
	procNtQueryInformationThread   = modntdll.NewProc("NtQueryInformationThread")
)

func _ContinueDebugEvent(processid uint32, threadid uint32, continuestatus uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procContinueDebugEvent.Addr(), uintptr(processid), uintptr(threadid), uintptr(continuestatus))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _DebugActiveProcess(processid uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procDebugActiveProcess.Addr(), uintptr(processid))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _DebugActiveProcessStop(processid uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procDebugActiveProcessStop.Addr(), uintptr(processid))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _DebugBreakProcess(process syscall.Handle) (err error) {
	r1, _, e1 := syscall.SyscallN(procDebugBreakProcess.Addr(), uintptr(process))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _FlushInstructionCache(process syscall.Handle, baseaddr uintptr, size uintptr) (err error) {
	r1, _, e1 := syscall.SyscallN(procFlushInstructionCache.Addr(), uintptr(process), uintptr(baseaddr), uintptr(size))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GetThreadContext(thread syscall.Handle, context *_CONTEXT) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetThreadContext.Addr(), uintptr(thread), uintptr(unsafe.Pointer(context)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _IsWow64Process(process syscall.Handle, wow64process *uint32) (ok uint32) {
	r0, _, _ := syscall.SyscallN(procIsWow64Process.Addr(), uintptr(process), uintptr(unsafe.Pointer(wow64process)))
	ok = uint32(r0)
	return
}

func _QueryFullProcessImageName(process syscall.Handle, flags uint32, exename *uint16, size *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procQueryFullProcessImageNameW.Addr(), uintptr(process), uintptr(flags), uintptr(unsafe.Pointer(exename)), uintptr(unsafe.Pointer(size)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _ReadProcessMemory(process syscall.Handle, baseaddr uintptr, buffer *byte, size uintptr, bytesread *uintptr) (err error) {
	r1, _, e1 := syscall.SyscallN(procReadProcessMemory.Addr(), uintptr(process), uintptr(baseaddr), uintptr(unsafe.Pointer(buffer)), uintptr(size), uintptr(unsafe.Pointer(bytesread)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _ResumeThread(threadid syscall.Handle) (prevsuspcount uint32, err error) {
	r0, _, e1 := syscall.SyscallN(procResumeThread.Addr(), uintptr(threadid))
	prevsuspcount = uint32(r0)
	if prevsuspcount == 0xffffffff {
		err = errnoErr(e1)
	}
	return
}

func _SetThreadContext(thread syscall.Handle, context *_CONTEXT) (err error) {
	r1, _, e1 := syscall.SyscallN(procSetThreadContext.Addr(), uintptr(thread), uintptr(unsafe.Pointer(context)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _SuspendThread(threadid syscall.Handle) (prevsuspcount uint32, err error) {
	r0, _, e1 := syscall.SyscallN(procSuspendThread.Addr(), uintptr(threadid))
	prevsuspcount = uint32(r0)
	if prevsuspcount == 0xffffffff {
		err = errnoErr(e1)
	}
	return
}

func _VirtualQueryEx(process syscall.Handle, addr uintptr, buffer *_MEMORY_BASIC_INFORMATION, length uintptr) (lengthOut uintptr) {
	r0, _, _ := syscall.SyscallN(procVirtualQueryEx.Addr(), uintptr(process), uintptr(addr), uintptr(unsafe.Pointer(buffer)), uintptr(length))
	lengthOut = uintptr(r0)
	return
}

func _WaitForDebugEvent(debugevent *_DEBUG_EVENT, milliseconds uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWaitForDebugEvent.Addr(), uintptr(unsafe.Pointer(debugevent)), uintptr(milliseconds))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _WriteProcessMemory(process syscall.Handle, baseaddr uintptr, buffer *byte, size uintptr, byteswritten *uintptr) (err error) {
	r1, _, e1 := syscall.SyscallN(procWriteProcessMemory.Addr(), uintptr(process), uintptr(baseaddr), uintptr(unsafe.Pointer(buffer)), uintptr(size), uintptr(unsafe.Pointer(byteswritten)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func _NtQueryInformationThread(threadHandle syscall.Handle, infoclass int32, info *_THREAD_BASIC_INFORMATION, infolen uint32, retlen *uint32) (status _NTSTATUS) {
	r0, _, _ := syscall.SyscallN(procNtQueryInformationThread.Addr(), uintptr(threadHandle), uintptr(infoclass), uintptr(unsafe.Pointer(info)), uintptr(infolen), uintptr(unsafe.Pointer(retlen)))
	status = _NTSTATUS(r0)
	return
}
