package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GoDelveDelve1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("GoDelveDelve1")
    name = "go-delve/delve (1)"
    url = "https://github.com/go-delve/delve"
    branch = "refs/heads/master"
    branchSpec = "+:refs/heads/feature-*"
    authMethod = password {
        userName = "DelveBot"
        password = "credentialsJSON:ae622caf-644c-4e69-bba8-2bea3e677ae9"
    }
}))

