// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package proc

import "unsafe"
import "syscall"

var _ unsafe.Pointer

var (
	modntdll = syscall.NewLazyDLL("ntdll.dll")

	procNtQueryInformationThread = modntdll.NewProc("NtQueryInformationThread")
)

func _NtQueryInformationThread(threadHandle syscall.Handle, infoclass int32, info uintptr, infolen uint32, retlen *uint32) (status _NTSTATUS) {
	r0, _, _ := syscall.Syscall6(procNtQueryInformationThread.Addr(), 5, uintptr(threadHandle), uintptr(infoclass), uintptr(info), uintptr(infolen), uintptr(unsafe.Pointer(retlen)), 0)
	status = _NTSTATUS(r0)
	return
}
